### ISSUE TITLE
Use JSOptionBuilder to build configuration objects

### ISSUE THREAD

**Issue by ludovicc** [jokade/scalajs-angulate#36]
Configuration objects such as Route or HttpConfig are difficult to build and verbose.

Querki uses an interesting builder pattern, [JSOptionBuilder](https://github.com/jducoeur/Querki/blob/master/querki/scalajs/src/main/scala/org/querki/jsext/JSOptionBuilder.scala), which we could copy, prossibly improve on with macros to reduce verbosity further, and make available to other angulate-based libraries (my uirouter, ionic libraries)

Here is an example of a builder for a configuration object: [DialogOptionBuilder](https://github.com/jducoeur/Querki/blob/master/querki/scalajs/src/main/scala/org/querki/facades/jqueryui/JQueryUIDialog.scala#L31) and this is how it's used: [Dialog](https://github.com/jducoeur/Querki/blob/master/querki/scalajs/src/main/scala/querki/display/Dialog.scala#L40)

**Comment by jokade** [comment]
I didn’t look into the details of JSOptionBuilder yet; I think its main advantage is that
you can reuse pre-configured option dictionaries. Otherwise, I’m not sure
if the method chaining used by the JSOptionBuilder approach is really less difficult
or verbose than named parameters?

But since it would be optional to use the builders, we probably should provide them.

**Comment by jokade** [comment]
@ludovicc Do you still think we need a builder for configuration objects?

**Comment by ludovicc** [comment]
Probably. It's now a library, and I'm using it for angular-ui configuration, it works well. Directives and router configuration could use it.

**Comment by jokade** [comment]
We can use case classes annotated with `@JSOptionsObject` (provided by smacrotools-sjs) instead.
