### ISSUE TITLE
Simplify Controller / controllerAs implementation

### ISSUE THREAD

**Issue by ludovicc** [jokade/scalajs-angulate#43]
It seems easier to use @JsExportAll to expose the contents of Controllers rather than using a macro, and  methods defined in a controller can be used from a template, where the macro expansion failed to do that properly (names are exposed in the scope with additional $)

Branch controller-reworks contains this rewrite.

**Comment by jokade** [comment]
You're right, `JSExportAll` is much simpler.
However, I can't get the following example to work with your changes:

``` scala
@JSExportAll
class FooCtrl extends Controller {
  val name = "Bar"
}

module.controllerOf[FooCtrl]
```

``` html
<!-- ... -->
<div ng-controller="FooCtrl as ctrl">Hello {{ctrl.name}}</div>
```

`name` is not set on `ctrl` (it's actually an empty object); this is probably due to the fact, that the constructor function in `ControllerMacros.createScopeController()` now is of type `js.Function` instead of `js.ThisFunction`? Or do you propose to drop the "controllerAs" syntax altogether?
